--- #YAML:1.0
name:               Net-SMTP-OneLiner
version:            2.0005
abstract:           ~
author:
    - Paul Miller <jettero@cpan.org>
license:            Perl Artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::SMTP:  0
    perl:       5.006001
resources:
    repository:  http://github.com/jettero/net--smtp--oneliner
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - smtp
    - one liner
    - one off
    - easy
    - simple
